### ISSUE TITLE
Publishing on npm

### ISSUE THREAD

**Issue by stof** [s9e/emoji-assets-noto#1]
Publishing this package on npm would make the assets available on https://www.jsdelivr.com/

**Comment by JoshyPHP** [comment]
AFAIK, all GitHub projects are accessible via jsDelivr by default. For instance: https://cdn.jsdelivr.net/gh/s9e/emoji-assets-noto/dist/svgz/1f929.svgz

<img width="40" src="https://cdn.jsdelivr.net/gh/s9e/emoji-assets-noto/dist/svgz/1f929.svgz">

**Comment by JoshyPHP** [comment]
The README has been updated to describe how to use jsDelivr as CDN.
